import React from 'react';

export interface TutorialStepInfo {
    showHint?: boolean; // automatically displays hint
    showDialog?: boolean; // no coding, displays in modal
    resetDiff?: boolean; // reset diffify algo
    tutorialCompleted?: boolean;

    // Step content
    title?: string;
    activity?: number;
    headerContentMd?: string;
    hintContentMd?: string;

    // Not used
    contentMd?: string;
}

export interface TutorialInfo {
    title: string;
    steps: TutorialStepInfo[];
    code?: string[];
}

export type HintLanguage = "markdown" | "typescript" | "blocks" | "spy";

export interface TutorialHint {
    language: HintLanguage;
    text: string;
}

let galgaSteps: TutorialStepInfo[] = [
    {
        "contentMd": "**In this tutorial, you'll create a space plane\nthat can fly through bogey spacecraft.**\n\nCan you survive the continuous attack?\n\n![Space plane and attacking spacecraft](/static/tutorials/galga.gif)",
        "headerContentMd": "**In this tutorial, you'll create a space plane\nthat can fly through bogey spacecraft.**\n\nCan you survive the continuous attack?",
        "showDialog": true,
        "hintContentMd": "![Space plane and attacking spacecraft](/static/tutorials/galga.gif)"
    },
    {
        "contentMd": "✈️ First, we're going to need a **space plane** [__*sprite*__](#sprite \"2-D image that moves on the screen\") ✈️\n\n---\n\n► From the ``||sprites:Sprites||`` category, grab a\n``||variables:set [mySprite] to sprite [ ] of kind [Player]||`` block and\nsnap it into the **on start** block already in the workspace.\n\n► Click on the word ``||variables:[mySprite]||`` in the new block to\nrename the variable ``||variables:[spacePlane]||``.\n\n► Now click inside the grey box in the new block to open the image editor.\nDraw a plane or choose something from the Gallery.\n\n\n```blocks\nlet spacePlane = sprites.create(img`\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . 8 2 . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . 1 1 1 . . . . . 9 9 9 9 9 . . . . . . . . . . . . . . .\n    . . . . 2 2 2 2 . . . 9 9 9 9 9 9 9 . . . . . . . . . . . . . .\n    . 4 4 4 f 8 6 6 6 6 6 6 9 9 9 9 9 6 6 6 . . . . . . . . . . . .\n    4 4 4 f 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 . . . . . . . . .\n    . 4 4 f 6 8 8 8 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 . . . . . . . .\n    . . 4 4 f 8 8 . . . . . 8 8 8 8 6 6 6 6 6 6 6 . . . . . . . . .\n    . . . . . . . . . . . 8 8 8 8 8 8 2 . . . . . . . . . . . . . .\n    . . . . . . . . . . . 8 8 8 8 8 2 . . . . . . . . . . . . . . .\n    . . . . . . . . . . 8 8 8 8 8 2 . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n`, SpriteKind.Player)\n```",
        "headerContentMd": "✈️ First, we're going to need a **space plane** [__*sprite*__](#sprite \"2-D image that moves on the screen\") ✈️\n\n---\n\n► From the ``||sprites:Sprites||`` category, grab a\n``||variables:set [mySprite] to sprite [ ] of kind [Player]||`` block and\nsnap it into the **on start** block already in the workspace.\n\n► Click on the word ``||variables:[mySprite]||`` in the new block to\nrename the variable ``||variables:[spacePlane]||``.\n\n► Now click inside the grey box in the new block to open the image editor.\nDraw a plane or choose something from the Gallery.",
        "hintContentMd": "```blocks\nlet spacePlane = sprites.create(img`\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . 8 2 . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . 1 1 1 . . . . . 9 9 9 9 9 . . . . . . . . . . . . . . .\n    . . . . 2 2 2 2 . . . 9 9 9 9 9 9 9 . . . . . . . . . . . . . .\n    . 4 4 4 f 8 6 6 6 6 6 6 9 9 9 9 9 6 6 6 . . . . . . . . . . . .\n    4 4 4 f 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 . . . . . . . . .\n    . 4 4 f 6 8 8 8 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 . . . . . . . .\n    . . 4 4 f 8 8 . . . . . 8 8 8 8 6 6 6 6 6 6 6 . . . . . . . . .\n    . . . . . . . . . . . 8 8 8 8 8 8 2 . . . . . . . . . . . . . .\n    . . . . . . . . . . . 8 8 8 8 8 2 . . . . . . . . . . . . . . .\n    . . . . . . . . . . 8 8 8 8 8 2 . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n`, SpriteKind.Player)\n```"
    },
    {
        "contentMd": "**Great plane!  Let's get it moving!**\n\n---\n\n► Find the ``||controller:move [mySprite] with buttons ⊕||`` block\nand drag it into the bottom of the ``||loops:on start||`` container.\n\n► Change **mySprite** to **spacePlane**.\n\n► Click the ⊕ at the right of the new block so you can change the\nmovement speed to **200** for both **vx** and **vy**.\n\n---\n\nNow your ship will move with the joystick or the **W A S D** keys.\nTry moving your ship around in the simulator!\n<br/>\n\n```blocks\nlet spacePlane = sprites.create(img`\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . 8 2 . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . 1 1 1 . . . . . 9 9 9 9 9 . . . . . . . . . . . . . . .\n    . . . . 2 2 2 2 . . . 9 9 9 9 9 9 9 . . . . . . . . . . . . . .\n    . 4 4 4 f 8 6 6 6 6 6 6 9 9 9 9 9 6 6 6 . . . . . . . . . . . .\n    4 4 4 f 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 . . . . . . . . .\n    . 4 4 f 6 8 8 8 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 . . . . . . . .\n    . . 4 4 f 8 8 . . . . . 8 8 8 8 6 6 6 6 6 6 6 . . . . . . . . .\n    . . . . . . . . . . . 8 8 8 8 8 8 2 . . . . . . . . . . . . . .\n    . . . . . . . . . . . 8 8 8 8 8 2 . . . . . . . . . . . . . . .\n    . . . . . . . . . . 8 8 8 8 8 2 . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n`, SpriteKind.Player)\n// @highlight\ncontroller.moveSprite(spacePlane, 200, 200)\n```",
        "headerContentMd": "**Great plane!  Let's get it moving!**\n\n---\n\n► Find the ``||controller:move [mySprite] with buttons ⊕||`` block\nand drag it into the bottom of the ``||loops:on start||`` container.\n\n► Change **mySprite** to **spacePlane**.\n\n► Click the ⊕ at the right of the new block so you can change the\nmovement speed to **200** for both **vx** and **vy**.\n\n---\n\nNow your ship will move with the joystick or the **W A S D** keys.\nTry moving your ship around in the simulator!\n<br/>",
        "hintContentMd": "```blocks\nlet spacePlane = sprites.create(img`\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . 8 2 . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . 1 1 1 . . . . . 9 9 9 9 9 . . . . . . . . . . . . . . .\n    . . . . 2 2 2 2 . . . 9 9 9 9 9 9 9 . . . . . . . . . . . . . .\n    . 4 4 4 f 8 6 6 6 6 6 6 9 9 9 9 9 6 6 6 . . . . . . . . . . . .\n    4 4 4 f 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 . . . . . . . . .\n    . 4 4 f 6 8 8 8 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 . . . . . . . .\n    . . 4 4 f 8 8 . . . . . 8 8 8 8 6 6 6 6 6 6 6 . . . . . . . . .\n    . . . . . . . . . . . 8 8 8 8 8 8 2 . . . . . . . . . . . . . .\n    . . . . . . . . . . . 8 8 8 8 8 2 . . . . . . . . . . . . . . .\n    . . . . . . . . . . 8 8 8 8 8 2 . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\n`, SpriteKind.Player)\n// @highlight\ncontroller.moveSprite(spacePlane, 200, 200)\n```"
    },
    {
        "contentMd": "🎆 **Congratulations** 🎆\n\nYou have completed your game!\n\nYou can now use the direction buttons to move your space plane and\nthe **Ⓐ** button to lauch darts!\n\n![Space plane and attacking spacecraft](/static/tutorials/galga.gif)",
        "headerContentMd": "🎆 **Congratulations** 🎆\n\nYou have completed your game!\n\nYou can now use the direction buttons to move your space plane and\nthe **Ⓐ** button to lauch darts!",
        "hintContentMd": "![Space plane and attacking spacecraft](/static/tutorials/galga.gif)"
    }
]

export const tutorial = {
    title: "New Tutorial",
    steps: galgaSteps
};

export const TutorialContext = React.createContext( {
    tutorial,
    setSteps: (newSteps: TutorialStepInfo[]) => {},
    updateStep: (index: number, newStep: TutorialStepInfo) => {}
});